services:
  frontend:
    build: ./front-end
    ports:
      - "8501:8501"
    volumes:
      - ./front-end:/app
      - ./.streamlit:/app/.streamlit
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - app_network

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - customer_data:/data
    env_file:
      - .env
    networks:
      - app_network

volumes:
  frontend_venv:
  customer_data:
    name: loan_calculator_customer_data

networks:
  app_network:
    driver: bridge
    attachable: true
