services:
  frontend:
    build:
      context: ./feature/streamlit-ui
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    networks:
      - loan_network

  backend:
    build:
      context: ./feature/fastapi-logic
      dockerfile: Dockerfile
    networks:
      - loan_network

networks:
  loan_network:
    driver: bridge
