services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    networks:
      - loan_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - loan_network

networks:
  loan_network:
    driver: bridge
