services:
  frontend:
    build: 
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./front-end:/app
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - app_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - customer_data:/data
    environment:
      - ENVIRONMENT=development
    networks:
      - app_network

volumes:
  customer_data:
    name: loan_calculator_customer_data

networks:
  app_network:
    driver: bridge
    attachable: true