services:
  frontend:
    build: 
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./front-end:/app
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - customer_data:/data
    environment:
      - ENVIRONMENT=development

volumes:
  customer_data:
    name: loan_calculator_customer_data 